workflows:
  ios-workflow:
    name: iOS Workflow

    environment:
      xcode: latest

    scripts:
      - name: Install Tuist
        script: |
          curl -fsSL https://mise.run | sh
          export PATH="$HOME/.local/bin:$HOME/.local/share/mise/shims:$PATH"
          mise install tuist@latest
          mise use -g tuist@latest
          tuist version

      - name: Generate Project
        script: |
          export PATH="$HOME/.local/bin:$HOME/.local/share/mise/shims:$PATH"
          tuist generate

      - name: Build IPA
        script: |
          xcodebuild archive \
          -workspace BudgetTracker.xcworkspace \
          -scheme BudgetTracker \
          -archivePath build/BudgetTracker.xcarchive

    artifacts:
      - build/**/*.ipa
      - build/**/*.xcarchive