workflows:
  ios-workflow:
    name: iOS Workflow

    environment:
      xcode: latest

    scripts:
      - name: Install Tuist
        script: |
          curl -fsSL https://mise.run | sh
          echo "$HOME/.local/bin" >> $CM_ENV
          mise install tuist
          mise use -g tuist@latest

      - name: Generate Project
        script: |
          tuist generate

      - name: Build IPA
        script: |
          xcodebuild archive \
          -workspace BudgetTracker.xcworkspace \
          -scheme BudgetTracker \
          -archivePath build/BudgetTracker.xcarchive

    artifacts:
      - build/**/*.ipa